apiVersion: v1
kind: Service
metadata:
  name: gcpgetstarted-service-$BRANCH_NAME
spec:
  type: LoadBalancer
  selector:
    app: gcpgetstarted-$BRANCH_NAME
  ports:
  - port: 80
    targetPort: 8080
