name: Deploy to GKE

on: 
  push:
    branches:
    - main
    - next

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: asia-east1-a
  DEPLOYMENT_NAME: gke-get-started-app
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
    - uses: actions/checkout@v3
    - name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Deploy
      run: |-
        set -x
        gcloud builds submit \
          --tag asia-east1-docker.pkg.dev/$PROJECT_ID/gke-get-started-repo/gcpgetstarted-python-$BRANCH_NAME python
        envsubst < deployment.yaml | kubectl apply -f -
        kubectl rollout status deployment/gcpgetstarted-deployment-$BRANCH_NAME
        envsubst < service.yaml | kubectl apply -f -
        kubectl get services
